name: Unittest CircularBuffer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install CUNIT and XALAN
      run: sudo apt install -y libcunit1-doc libcunit1-dev xalan
    - name: make
      run: make -C c/CircularBuffer/cunit
    - name: Translate cunit to junit
      run: |
        wget -O c/CircularBuffer/cunit/cunit-to-junit.xsl https://raw.githubusercontent.com/shawnliang/cunit-to-junit/master/cunit-to-junit.xsl
        cp /usr/share/CUnit/* c/CircularBuffer/cunit
        xalan -xsl c/CircularBuffer/cunit/cunit-to-junit.xsl -in c/CircularBuffer/cunit/CircularBuffer-Results.xml -out c/CircularBuffer/cunit/CircularBuffer-Results-JUnit.xml
    
